---
 - name: Create Ec2 instance
   hosts: localhost
   connection: local
   gather_facts: False
   tags: provisioning

   vars:
     key_name: ali_ilk_key
     instance_type: t2.micro
     image: ami-0e472ba40eb589f49
     wait: yes
     group: monitoring servers
     count: 1
     region: us-east-1
     security_group: Security group for grafana server
     user_data: "{{ lookup('file', 'user-data.sh') }}"

   tasks:
     - name: Creating security group for grafana server
       local_action:
         module: ec2_group
         name: "{{ security_group }}"
         description: Security group for grafana server
         region: "{{ region }}"
         rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 4000
              to_port: 4000
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8090
              to_port: 8090
              cidr_ip: 0.0.0.0/0
         rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
       register: basic_firewall
     - name: Launching the new EC2 Instance which is created for grafana server
       local_action:  ec2
                      group={{ security_group }}
                      instance_type={{ instance_type }}
                      image={{ image }}
                      wait=true
                      region={{ region }}
                      user_data="{{ user_data }}"
                      key_name={{ key_name }}
                      count={{ count }}
                      
       register: ec2
     - name: Add Tagging to EC2 instance
       local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
       with_items: "{{ ec2.instances }}"
       args:
         tags:
           Name: New Instance for Grafana Server
           Monitoring: New Instance for Grafana Server